### PR TITLE
Team Component

### PR DESCRIPTION
**Pull request by BrandonAlexanderLopez**
* **Please check if the PR fulfills these requirements**
- [x] The pull request title contains the ticket number in the title. For example [CB-1]
CHECK

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
Includes the back end team members in card form.
Contains their name, school, classification, bio, and link to github.

* **What is the current behavior?What does the code do before you made the new changes?** 
We now have a teams list, before there was no teams list.

* **What is the new behavior?**
We have a team component that displays the developers and includes a link to their github.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)
Nothing breaks, HOWEVER picture formatting does not seem to work. No matter how small the pic being uploaded is, the image on the site takes up the whole page. I don't know why...

* **Other information**:
OUTPUT:
image

### CODE REVIEW

**Comment by BrandonAlexanderLopez** [comment]
OUTPUT:
image

**Comment by Codubee** [comment]
Looks good, just gotta add the front end team here.

**Comment by BrandonAlexanderLopez** [comment]
image
This is the current output, I'm a little confused about the merging conflicts... the symbols and everything is throwing me off.

**Review by Codubee — DISMISSED** [review]
LGTM!

**Pull request merged**
